name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull iamyaseer/server-cicd:latest
      - name: Stop Existing Docker Container
        run: sudo docker stop server-cicd || true
      - name: Delete Old docker container
        run: sudo docker rm -f server-cicd || true
      - name: Run Docker Container
        run: docker run -d -p 80:3000 --name server-cicd iamyaseer/server-cicd:latest
